apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
namespace: cert-manager

# resources:
# - https://github.com/cert-manager/cert-manager/releases/download/v1.11.5/cert-manager.crds.yaml

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  version: 1.11.5
  repo: https://charts.jetstack.io
  valuesInline:
    installCRDs: true
